-- Seed 003: minimal reference data for dm_categories/dm_category_items.
-- The seed is intentionally conservative and uses only broad codes required
-- by the current schema, README, AGENTS rules and existing skills.

INSERT INTO dm_categories (category_code, category_name, description, sort_order)
VALUES
    ('court_level', 'Cap toa an', 'Cap Toa an dang duoc giu bang PostgreSQL enum trong schema goc.', 1),
    ('user_role', 'Vai tro nguoi dung', 'Vai tro nguoi dung dang duoc giu bang PostgreSQL enum trong schema goc.', 2),
    ('case_type', 'Loai an', 'Loai an dang duoc giu bang PostgreSQL enum trong schema goc.', 10),
    ('case_group', 'Nhom an', 'Nhom nghiep vu dung cho thong ke, KPI va phan cong.', 20),
    ('procedure_law', 'Luat to tung', 'Van ban to tung lam nen tang xu ly ho so.', 30),
    ('case_stage', 'Giai doan ho so', 'Giai doan vong doi ho so vu an/vu viec.', 40),
    ('case_status', 'Trang thai ho so', 'Trang thai ho so dang duoc giu bang PostgreSQL enum trong schema goc.', 50),
    ('participant_type', 'Loai nguoi tham gia to tung', 'Vai tro cua ca nhan/to chuc trong ho so.', 60),
    ('document_type', 'Loai tai lieu', 'Danh muc loai tai lieu trong ho so.', 70),
    ('decision_type', 'Loai ban an/quyet dinh', 'Danh muc loai van ban giai quyet cua Toa an.', 80),
    ('deadline_type', 'Loai thoi han', 'Loai thoi han can theo doi/canh bao.', 90),
    ('deadline_status', 'Trang thai thoi han', 'Trang thai xu ly thoi han.', 100),
    ('warning_level', 'Muc canh bao', 'Muc canh bao cho deadline/risk.', 110),
    ('validation_rule', 'Rule validation', 'Ma rule kiem tra du lieu toi thieu.', 120),
    ('validation_status', 'Trang thai validation', 'Trang thai xu ly ket qua validation.', 130),
    ('validation_severity', 'Muc do validation', 'Muc do validation/risk dang duoc giu bang PostgreSQL enum.', 135),
    ('kpi_group', 'Nhom KPI', 'Nhom chi tieu KPI va dashboard.', 140),
    ('appeal_protest_type', 'Loai khang cao khang nghi', 'Loai khang cao/khang nghi dang duoc giu bang PostgreSQL enum.', 150),
    ('appellate_result', 'Ket qua cap tren', 'Ket qua xet xu/giai quyet cua Toa an cap tren.', 160),
    ('fault_classification', 'Phan loai loi', 'Phan loai khach quan/chu quan/hon hop/chua xac dinh.', 170),
    ('fault_reason_group', 'Nhom ly do loi', 'Nhom ly do danh gia khi an bi huy/sua.', 180),
    ('assignment_role', 'Vai tro phan cong', 'Vai tro nguoi duoc phan cong trong ho so.', 190),
    ('assignment_method', 'Phuong thuc phan cong', 'Phuong thuc phan cong dang duoc giu bang PostgreSQL enum.', 200),
    ('assignment_status', 'Trang thai phan cong', 'Trang thai batch/assignment dang duoc giu bang PostgreSQL enum.', 210),
    ('tracking_status', 'Trang thai theo doi cap tren', 'Trang thai theo doi khang cao/khang nghi.', 220),
    ('item_status', 'Trang thai muc nghiep vu', 'Trang thai chung cho item/follow-up/AI.', 230),
    ('period_type', 'Loai ky thong ke', 'Thang, quy, nam hoac tuy chon.', 240),
    ('aggregation_level', 'Cap tong hop', 'Cap tong hop so lieu dashboard/thong ke.', 250),
    ('statistic_form', 'Bieu mau thong ke', 'Ma bieu mau thong ke, can bo sung theo PDF/JSON da duoc xac nhan.', 260),
    ('hearing_type', 'Loai phien toa/phien hop', 'Danh muc loai phien toa/phien hop.', 270),
    ('hearing_status', 'Trang thai phien toa/phien hop', 'Trang thai lich/phien toa/phien hop.', 280),
    ('appeal_status', 'Trang thai khang cao', 'Trang thai khang cao trong bang appeals cu.', 290),
    ('gender', 'Gioi tinh', 'Danh muc gioi tinh toi thieu.', 300),
    ('risk_type', 'Loai canh bao rui ro', 'Loai canh bao do rule/AI phat hien.', 310),
    ('audit_action', 'Hanh dong audit', 'Loai hanh dong ghi audit.', 320),
    ('ai_suggestion_type', 'Loai goi y AI', 'Loai goi y/canh bao do AI tao.', 330)
ON CONFLICT (category_code) DO UPDATE SET
    category_name = EXCLUDED.category_name,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;

WITH items(category_code, item_code, item_name, sort_order) AS (
    VALUES
        ('case_type', 'civil', 'Dan su', 10),
        ('court_level', 'province', 'Cap tinh', 10),
        ('court_level', 'district', 'Cap huyen', 20),
        ('court_level', 'regional', 'Khu vuc', 30),
        ('court_level', 'military', 'Quan su', 40),
        ('court_level', 'upper', 'Cap tren', 50),
        ('court_level', 'supreme', 'Toi cao', 60),
        ('user_role', 'chief_judge', 'Chanh an', 10),
        ('user_role', 'deputy_chief_judge', 'Pho Chanh an', 20),
        ('user_role', 'judge', 'Tham phan', 30),
        ('user_role', 'clerk', 'Thu ky', 40),
        ('user_role', 'leader', 'Lanh dao', 50),
        ('user_role', 'admin', 'Quan tri', 60),
        ('user_role', 'viewer', 'Nguoi xem', 70),
        ('user_role', 'ai_agent', 'AI Agent', 80),
        ('case_type', 'marriage_family', 'Hon nhan gia dinh', 20),
        ('case_type', 'business_commercial', 'Kinh doanh thuong mai', 30),
        ('case_type', 'labor', 'Lao dong', 40),
        ('case_type', 'criminal', 'Hinh su', 50),
        ('case_type', 'administrative', 'Hanh chinh', 60),
        ('case_type', 'civil_matter', 'Viec dan su', 70),
        ('case_type', 'bankruptcy', 'Pha san', 80),
        ('case_type', 'administrative_measure', 'Bien phap hanh chinh', 90),
        ('case_type', 'other', 'Khac', 100),
        ('case_group', 'civil', 'Dan su', 10),
        ('case_group', 'criminal', 'Hinh su', 20),
        ('case_group', 'administrative', 'Hanh chinh', 30),
        ('case_group', 'marriage_family', 'Hon nhan gia dinh', 40),
        ('case_group', 'business_commercial', 'Kinh doanh thuong mai', 50),
        ('case_group', 'labor', 'Lao dong', 60),
        ('case_group', 'other', 'Khac', 100),
        ('procedure_law', 'BLTTDS', 'Bo luat To tung dan su', 10),
        ('procedure_law', 'BLTTHS', 'Bo luat To tung hinh su', 20),
        ('procedure_law', 'LTTHC', 'Luat To tung hanh chinh', 30),
        ('case_stage', 'received', 'Da nhan', 10),
        ('case_stage', 'accepted', 'Da thu ly', 20),
        ('case_stage', 'preparing', 'Dang chuan bi', 30),
        ('case_stage', 'trial_scheduled', 'Da len lich xet xu', 40),
        ('case_stage', 'resolved', 'Da giai quyet', 50),
        ('case_stage', 'appeal_tracking', 'Dang theo doi cap tren', 60),
        ('case_stage', 'closed', 'Da dong ho so', 70),
        ('case_status', 'draft', 'Nhap nhap', 10),
        ('case_status', 'received', 'Da nhan', 20),
        ('case_status', 'accepted', 'Da thu ly', 30),
        ('case_status', 'preparing', 'Dang chuan bi', 40),
        ('case_status', 'trial_scheduled', 'Da len lich xet xu', 50),
        ('case_status', 'resolved', 'Da giai quyet', 60),
        ('case_status', 'appealed', 'Bi khang cao/khang nghi', 70),
        ('case_status', 'effective', 'Da co hieu luc', 80),
        ('case_status', 'temporarily_suspended', 'Tam dinh chi', 90),
        ('case_status', 'suspended', 'Dinh chi', 100),
        ('case_status', 'overdue', 'Qua han', 110),
        ('case_status', 'closed', 'Da dong', 120),
        ('participant_type', 'plaintiff', 'Nguyen don', 10),
        ('participant_type', 'defendant', 'Bi don', 20),
        ('participant_type', 'appellant', 'Nguoi khang cao', 30),
        ('participant_type', 'victim', 'Bi hai', 40),
        ('participant_type', 'procuracy', 'Vien kiem sat', 50),
        ('participant_type', 'agency', 'Co quan/to chuc', 60),
        ('participant_type', 'other', 'Khac', 100),
        ('document_type', 'petition', 'Don khoi kien/yeu cau', 10),
        ('document_type', 'indictment', 'Cao trang', 20),
        ('document_type', 'judgment', 'Ban an', 30),
        ('document_type', 'decision', 'Quyet dinh', 40),
        ('document_type', 'appeal_document', 'Don khang cao', 50),
        ('document_type', 'protest_document', 'Quyet dinh khang nghi', 60),
        ('document_type', 'evidence', 'Tai lieu chung cu', 70),
        ('document_type', 'other', 'Khac', 100),
        ('decision_type', 'judgment', 'Ban an', 10),
        ('decision_type', 'decision', 'Quyet dinh', 20),
        ('decision_type', 'settlement_recognition', 'Cong nhan thoa thuan', 30),
        ('decision_type', 'suspension', 'Dinh chi', 40),
        ('decision_type', 'temporary_suspension', 'Tam dinh chi', 50),
        ('deadline_type', 'preparation', 'Thoi han chuan bi xet xu/giai quyet', 10),
        ('deadline_type', 'detention', 'Thoi han tam giam', 20),
        ('deadline_type', 'appeal', 'Thoi han khang cao', 30),
        ('deadline_type', 'protest', 'Thoi han khang nghi', 40),
        ('deadline_type', 'enforcement', 'Thoi han thi hanh/theo doi', 50),
        ('deadline_type', 'validation_followup', 'Thoi han xu ly validation', 60),
        ('deadline_status', 'pending', 'Dang theo doi', 10),
        ('deadline_status', 'due_soon', 'Sap het han', 20),
        ('deadline_status', 'overdue', 'Qua han', 30),
        ('deadline_status', 'completed', 'Da hoan thanh', 40),
        ('deadline_status', 'extended', 'Da gia han', 50),
        ('warning_level', 'INFO', 'Thong tin', 10),
        ('warning_level', 'WARNING', 'Canh bao', 20),
        ('warning_level', 'ERROR', 'Loi', 30),
        ('warning_level', 'CRITICAL', 'Nghiem trong', 40),
        ('validation_rule', 'missing_acceptance_date', 'Thieu ngay thu ly', 10),
        ('validation_rule', 'missing_case_type', 'Thieu loai an', 20),
        ('validation_rule', 'missing_primary_judge', 'Thieu Tham phan duoc phan cong', 30),
        ('validation_rule', 'overdue_preparation', 'Qua han chuan bi xet xu', 40),
        ('validation_rule', 'missing_upper_result', 'Thieu ket qua cap tren', 50),
        ('validation_rule', 'duplicate_statistics', 'Du lieu thong ke bi dem trung', 60),
        ('validation_status', 'open', 'Dang mo', 10),
        ('validation_status', 'resolved', 'Da xu ly', 20),
        ('validation_status', 'ignored', 'Bo qua co ly do', 30),
        ('validation_severity', 'INFO', 'Thong tin', 10),
        ('validation_severity', 'WARNING', 'Canh bao', 20),
        ('validation_severity', 'ERROR', 'Loi', 30),
        ('validation_severity', 'CRITICAL', 'Nghiem trong', 40),
        ('kpi_group', 'case_volume', 'Khoi luong an', 10),
        ('kpi_group', 'case_quality', 'Chat luong xet xu', 20),
        ('kpi_group', 'deadline', 'Thoi han', 30),
        ('kpi_group', 'appeal_protest', 'Khang cao/khang nghi', 40),
        ('kpi_group', 'random_assignment', 'Phan cong ngau nhien', 50),
        ('kpi_group', 'mediation_dialogue', 'Hoa giai/doi thoai', 60),
        ('appeal_protest_type', 'APPEAL', 'Khang cao', 10),
        ('appeal_protest_type', 'PROTEST', 'Khang nghi', 20),
        ('appeal_protest_type', 'BOTH', 'Co ca khang cao va khang nghi', 30),
        ('appellate_result', 'uphold', 'Giu nguyen', 10),
        ('appellate_result', 'modified', 'Sua', 20),
        ('appellate_result', 'cancelled', 'Huy', 30),
        ('appellate_result', 'remanded', 'Giao xet xu/giai quyet lai', 40),
        ('appellate_result', 'terminated', 'Dinh chi', 50),
        ('appellate_result', 'withdrawn', 'Rut khang cao/khang nghi', 60),
        ('appellate_result', 'other', 'Khac', 100),
        ('fault_classification', 'objective', 'Khach quan', 10),
        ('fault_classification', 'subjective', 'Chu quan', 20),
        ('fault_classification', 'mixed', 'Hon hop', 30),
        ('fault_classification', 'unknown', 'Chua xac dinh', 40),
        ('fault_reason_group', 'procedure', 'Thu tuc to tung', 10),
        ('fault_reason_group', 'evidence_assessment', 'Danh gia chung cu', 20),
        ('fault_reason_group', 'law_application', 'Ap dung phap luat', 30),
        ('fault_reason_group', 'objective_change', 'Tinh tiet khach quan thay doi', 40),
        ('fault_reason_group', 'unknown', 'Chua xac dinh', 50),
        ('assignment_role', 'primary_judge', 'Tham phan chinh', 10),
        ('assignment_role', 'panel_judge', 'Thanh vien Hoi dong xet xu', 20),
        ('assignment_role', 'clerk', 'Thu ky', 30),
        ('assignment_method', 'RANDOM', 'Ngau nhien', 10),
        ('assignment_method', 'DESIGNATED', 'Chi dinh', 20),
        ('assignment_method', 'MIXED', 'Ket hop', 30),
        ('assignment_status', 'draft', 'Nhap nhap', 10),
        ('assignment_status', 'running', 'Dang chay', 20),
        ('assignment_status', 'completed', 'Hoan thanh', 30),
        ('assignment_status', 'cancelled', 'Da huy', 40),
        ('assignment_status', 'active', 'Dang hieu luc', 50),
        ('assignment_status', 'replaced', 'Da thay the', 60),
        ('tracking_status', 'received', 'Da nhan', 10),
        ('tracking_status', 'sent_to_upper_court', 'Da gui Toa cap tren', 20),
        ('tracking_status', 'accepted', 'Toa cap tren da thu ly', 30),
        ('tracking_status', 'resolved', 'Da co ket qua cap tren', 40),
        ('tracking_status', 'closed', 'Da dong theo doi', 50),
        ('item_status', 'active', 'Dang hieu luc', 10),
        ('item_status', 'pending', 'Dang cho xu ly', 20),
        ('item_status', 'withdrawn', 'Da rut', 30),
        ('item_status', 'rejected', 'Khong duoc chap nhan', 40),
        ('item_status', 'resolved', 'Da xu ly', 50),
        ('item_status', 'closed', 'Da dong', 60),
        ('item_status', 'draft', 'Nhap nhap', 70),
        ('item_status', 'pending_review', 'Cho duyet', 80),
        ('period_type', 'month', 'Thang', 10),
        ('period_type', 'quarter', 'Quy', 20),
        ('period_type', 'year', 'Nam', 30),
        ('period_type', 'custom', 'Tuy chon', 40),
        ('aggregation_level', 'province', 'Toan tinh', 10),
        ('aggregation_level', 'court', 'Theo Toa an', 20),
        ('aggregation_level', 'judge', 'Theo Tham phan', 30),
        ('aggregation_level', 'case', 'Theo ho so', 40),
        ('hearing_type', 'trial', 'Phien toa', 10),
        ('hearing_type', 'meeting', 'Phien hop', 20),
        ('hearing_status', 'scheduled', 'Da len lich', 10),
        ('hearing_status', 'opened', 'Da mo', 20),
        ('hearing_status', 'postponed', 'Hoan', 30),
        ('hearing_status', 'closed', 'Ket thuc', 40),
        ('appeal_status', 'received', 'Da nhan', 10),
        ('appeal_status', 'sent', 'Da gui', 20),
        ('appeal_status', 'withdrawn', 'Da rut', 30),
        ('appeal_status', 'resolved', 'Da giai quyet', 40),
        ('gender', 'male', 'Nam', 10),
        ('gender', 'female', 'Nu', 20),
        ('gender', 'other', 'Khac', 30),
        ('risk_type', 'overdue_risk', 'Nguy co qua han', 10),
        ('risk_type', 'missing_data', 'Thieu du lieu', 20),
        ('risk_type', 'duplicate_data', 'Nguy co trung du lieu', 30),
        ('risk_type', 'appeal_quality', 'Rui ro chat luong qua ket qua cap tren', 40),
        ('audit_action', 'INSERT', 'Them moi', 10),
        ('audit_action', 'UPDATE', 'Cap nhat', 20),
        ('audit_action', 'DELETE', 'Xoa', 30),
        ('audit_action', 'ASSIGNMENT_RUN', 'Chay phan cong', 40),
        ('audit_action', 'VALIDATION_CHECK', 'Kiem tra validation', 50),
        ('ai_suggestion_type', 'validation', 'Goi y validation', 10),
        ('ai_suggestion_type', 'risk_warning', 'Canh bao rui ro', 20),
        ('ai_suggestion_type', 'report_summary', 'Tom tat bao cao', 30)
)
INSERT INTO dm_category_items (category_id, item_code, item_name, sort_order)
SELECT c.category_id, i.item_code, i.item_name, i.sort_order
FROM items i
JOIN dm_categories c ON c.category_code = i.category_code
ON CONFLICT (category_id, item_code) DO UPDATE SET
    item_name = EXCLUDED.item_name,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;

WITH bindings(category_code, table_name, source_column_name, reference_column_name, notes) AS (
    VALUES
        ('court_level', 'courts', 'court_level', 'court_level_id', 'Enum goc van giu lai trong phase 1.'),
        ('user_role', 'users', 'role_code', 'role_id', 'Enum goc van giu lai trong phase 1.'),
        ('case_type', 'case_files', 'case_type', 'case_type_id', 'Enum goc van giu lai trong phase 1.'),
        ('case_group', 'case_files', 'case_group', 'case_group_id', 'Chay song song voi text cu.'),
        ('procedure_law', 'case_files', 'procedure_law', 'procedure_law_id', 'Chay song song voi text cu.'),
        ('case_stage', 'case_files', 'current_stage', 'current_stage_id', 'Chay song song voi text cu.'),
        ('case_status', 'case_files', 'case_status', 'case_status_id', 'Enum goc van giu lai trong phase 1.'),
        ('participant_type', 'participants', 'participant_type', 'participant_type_id', 'Chay song song voi text cu.'),
        ('document_type', 'documents', 'document_type', 'document_type_id', 'Chay song song voi text cu.'),
        ('decision_type', 'decisions', 'decision_type', 'decision_type_id', 'Chay song song voi text cu.'),
        ('deadline_type', 'deadlines', 'deadline_type', 'deadline_type_id', 'Chay song song voi text cu.'),
        ('deadline_status', 'deadlines', 'deadline_status', 'deadline_status_id', 'Chay song song voi text cu.'),
        ('validation_rule', 'validation_results', 'rule_code', 'rule_id', 'Rule can tiep tuc bo sung tu validation_rules.json.'),
        ('validation_severity', 'validation_results', 'severity', 'severity_id', 'Enum goc van giu lai trong phase 1.'),
        ('validation_status', 'validation_results', 'validation_status', 'validation_status_id', 'Chay song song voi text cu.'),
        ('kpi_group', 'kpi_metrics', 'metric_group', 'metric_group_id', 'Chay song song voi text cu.'),
        ('period_type', 'statistics_periods', 'period_type', 'period_type_id', 'Chay song song voi text cu.'),
        ('aggregation_level', 'statistics_snapshots', 'aggregation_level', 'aggregation_level_id', 'Chay song song voi text cu.'),
        ('appeal_protest_type', 'appellate_trackings', 'appeal_protest_type', 'appeal_protest_type_id', 'Enum goc van giu lai trong phase 1.'),
        ('tracking_status', 'appellate_trackings', 'tracking_status', 'tracking_status_id', 'Chay song song voi text cu.'),
        ('appellate_result', 'appellate_trackings', 'final_result_code', 'final_result_id', 'Chay song song voi text cu.'),
        ('appellate_result', 'appellate_results', 'result_code', 'result_code_id', 'Chay song song voi text cu.'),
        ('fault_reason_group', 'appellate_fault_assessments', 'fault_reason_group', 'fault_reason_group_id', 'Chay song song voi text cu.'),
        ('assignment_role', 'case_assignments', 'assignment_role', 'assignment_role_id', 'Chay song song voi text cu.'),
        ('assignment_method', 'case_assignments', 'assignment_method', 'assignment_method_id', 'Enum goc van giu lai trong phase 1.'),
        ('assignment_status', 'case_assignments', 'status', 'status_id', 'Enum goc van giu lai trong phase 1.'),
        ('assignment_method', 'assignment_batches', 'assignment_method', 'assignment_method_id', 'Enum goc van giu lai trong phase 1.'),
        ('assignment_status', 'assignment_batches', 'status', 'status_id', 'Enum goc van giu lai trong phase 1.'),
        ('fault_classification', 'appellate_trackings', 'fault_classification', 'fault_classification_id', 'Enum goc van giu lai trong phase 1.'),
        ('appeal_protest_type', 'appeal_protest_items', 'item_type', 'item_type_id', 'Enum goc van giu lai trong phase 1.'),
        ('fault_classification', 'appellate_fault_assessments', 'fault_classification', 'fault_classification_id', 'Enum goc van giu lai trong phase 1.'),
        ('risk_type', 'case_risk_flags', 'risk_type', 'risk_type_id', 'Chay song song voi text cu.'),
        ('validation_severity', 'case_risk_flags', 'severity', 'severity_id', 'Enum goc van giu lai trong phase 1.'),
        ('item_status', 'case_risk_flags', 'status', 'status_id', 'Chay song song voi text cu.'),
        ('audit_action', 'audit_logs', 'action', 'action_id', 'Chay song song voi text cu.')
)
INSERT INTO dm_table_reference_columns (
    category_id, table_name, source_column_name, reference_column_name, notes
)
SELECT c.category_id, b.table_name, b.source_column_name, b.reference_column_name, b.notes
FROM bindings b
JOIN dm_categories c ON c.category_code = b.category_code
ON CONFLICT (category_id, table_name, COALESCE(source_column_name, ''), reference_column_name)
DO UPDATE SET notes = EXCLUDED.notes;
