-- Seed 021: Excel-derived criminal offense names.
-- Source: database/seed/danh sach/H?nh s? - S? th?m.xlsx
-- Source: database/seed/danh sach/H?nh s? - Ph?c th?m.xlsx
-- Only inserts a crime when no existing dm_crimes row has the same display name.

WITH src(crime_code, crime_name, source_document, notes, requires_human_review, sort_order) AS (
    VALUES
        ('excel_crime_ieu_332_toi_tron_tranh_nghia_vu_quan_su', 'Điều 332. Tội trốn tránh nghĩa vụ quân sự', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 1),
        ('excel_crime_nguoi_nao_tang_tru_trai_phep_chat_ma_tuy_ma_khong_nham_muc_ich_mua_ban_van_chuy_f4f570dd', 'Người nào tàng trữ trái phép chất ma túy mà không nhằm mục đích mua bán, vận chuyển, sản xuất trái phép chất ma túy thuộc một trong các trường hợp sau đây, thì bị phạt tù từ 01 năm đến 05 năm:', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 8', TRUE, 2),
        ('excel_crime_toi_anh_bac', 'Tội đánh bạc', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 200', TRUE, 3),
        ('excel_crime_toi_bao_loan', 'Tội bạo loạn', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 4),
        ('excel_crime_toi_bat_giu_hoac_giam_nguoi_trai_phap_luat', 'Tội bắt, giữ hoặc giam người trái pháp luật', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 36', TRUE, 5),
        ('excel_crime_toi_buon_lau', 'Tội buôn lậu', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 6),
        ('excel_crime_toi_che_tao_tang_tru_van_chuyen_su_dung_mua_ban_trai_phep_hoac_chiem_oat_vat_lieu_no', 'Tội chế tạo, tàng trữ, vận chuyển, sử dụng, mua bán trái phép hoặc chiếm đoạt vật liệu nổ', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 13', TRUE, 7),
        ('excel_crime_toi_che_tao_tang_tru_van_chuyen_su_dung_mua_ban_trai_phep_hoac_chiem_oat_vu_khi_eee1289c', 'Tội chế tạo, tàng trữ, vận chuyển, sử dụng, mua bán trái phép hoặc chiếm đoạt vũ khí quân dụng, phương tiện kỹ thuật quân sự', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 33', TRUE, 8),
        ('excel_crime_toi_cho_vay_lai_nang_trong_giao_dich_dan_su', 'Tội cho vay lãi nặng trong giao dịch dân sự', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 17', TRUE, 9),
        ('excel_crime_toi_chong_nguoi_thi_hanh_cong_vu', 'Tội chống người thi hành công vụ', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 4', TRUE, 10),
        ('excel_crime_toi_chua_chap_hoac_tieu_thu_tai_san_do_nguoi_khac_pham_toi_ma_co', 'Tội chứa chấp hoặc tiêu thụ tài sản do người khác phạm tội mà có', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 6', TRUE, 11),
        ('excel_crime_toi_chua_chap_viec_su_dung_trai_phep_chat_ma_tuy', 'Tội chứa chấp việc sử dụng trái phép chất ma túy', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 7', TRUE, 12),
        ('excel_crime_toi_chua_mai_dam', 'Tội chứa mại dâm', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 7', TRUE, 13),
        ('excel_crime_toi_co_y_gay_thuong_tich_hoac_gay_ton_hai_cho_suc_khoe_cua_nguoi_khac', 'Tội cố ý gây thương tích hoặc gây tổn hại cho sức khỏe của người khác', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 170', TRUE, 14),
        ('excel_crime_toi_co_y_lam_trai_quy_inh_cua_nha_nuoc_ve_quan_ly_kinh_te_gay_hau_qua_nghiem_trong', 'Tội cố ý làm trái quy định của Nhà nước về quản lý kinh tế gây hậu quả nghiêm trọng', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 6', TRUE, 15),
        ('excel_crime_toi_cuong_dam', 'Tội cưỡng dâm', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 16),
        ('excel_crime_toi_cuong_oat_tai_san', 'Tội cưỡng đoạt tài sản', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 6', TRUE, 17),
        ('excel_crime_toi_cuop_giat_tai_san', 'Tội cướp giật tài sản', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 18),
        ('excel_crime_toi_cuop_tai_san', 'Tội cướp tài sản', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 21', TRUE, 19),
        ('excel_crime_toi_dam_o_oi_voi_nguoi_duoi_16_tuoi', 'Tội dâm ô đối với người dưới 16 tuổi', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 5', TRUE, 20),
        ('excel_crime_toi_e_doa_giet_nguoi', 'Tội đe dọa giết người', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 21),
        ('excel_crime_toi_gay_roi_trat_tu_cong_cong', 'Tội gây rối trật tự công cộng', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 238', TRUE, 22),
        ('excel_crime_toi_gia_mao_trong_cong_tac', 'Tội giả mạo trong công tác', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 10', TRUE, 23),
        ('excel_crime_toi_giao_cau_hoac_thuc_hien_hanh_vi_quan_he_tinh_duc_khac_voi_nguoi_tu_u_13_tuo_896622ea', 'Tội giao cấu hoặc thực hiện hành vi quan hệ tình dục khác với người từ đủ 13 tuổi đến dưới 16 tuổi', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 14', TRUE, 24),
        ('excel_crime_toi_giao_cau_voi_tre_em', 'Tội giao cấu với trẻ em', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 25),
        ('excel_crime_toi_giet_nguoi', 'Tội giết người', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 498', TRUE, 26),
        ('excel_crime_toi_giet_nguoi_trong_trang_thai_tinh_than_bi_kich_ong_manh', 'Tội giết người trong trạng thái tinh thần bị kích động mạnh', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 4', TRUE, 27),
        ('excel_crime_toi_hiep_dam', 'Tội hiếp dâm', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 28),
        ('excel_crime_toi_hiep_dam_nguoi_duoi_16_tuoi', 'Tội hiếp dâm người dưới 16 tuổi', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 34', TRUE, 29),
        ('excel_crime_toi_hoat_ong_nham_lat_o_chinh_quyen_nhan_dan', 'Tội hoạt động nhằm lật đổ chính quyền nhân dân.', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 30),
        ('excel_crime_toi_huy_hoai_hoac_co_y_lam_hu_hong_tai_san', 'Tội hủy hoại hoặc cố ý làm hư hỏng tài sản', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 18', TRUE, 31),
        ('excel_crime_toi_huy_hoai_rung', 'Tội hủy hoại rừng', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 3', TRUE, 32),
        ('excel_crime_toi_in_phat_hanh_mua_ban_trai_phep_hoa_on_chung_tu_thu_nop_ngan_sach_nha_nuoc', 'Tội in, phát hành, mua bán trái phép hóa đơn, chứng từ thu nộp ngân sách nhà nước', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 8', TRUE, 33),
        ('excel_crime_toi_lam_dung_chuc_vu_quyen_han_chiem_oat_tai_san', 'Tội lạm dụng chức vụ, quyền hạn chiếm đoạt tài sản', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 3', TRUE, 34),
        ('excel_crime_toi_lam_dung_tin_nhiem_chiem_oat_tai_san', 'Tội lạm dụng tín nhiệm chiếm đoạt tài sản', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 20', TRUE, 35),
        ('excel_crime_toi_lam_gia_con_dau_tai_lieu_cua_co_quan_to_chuc', 'Tội làm giả con dấu, tài liệu của cơ quan, tổ chức', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 22', TRUE, 36),
        ('excel_crime_toi_lam_nhuc_nguoi_khac', 'Tội làm nhục người khác', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 37),
        ('excel_crime_toi_lam_tang_tru_phat_tan_hoac_tuyen_truyen_thong_tin_tai_lieu_vat_pham_nham_ch_0bb54ebd', 'Tội làm, tàng trữ, phát tán hoặc tuyên truyền thông tin, tài liệu, vật phẩm nhằm chống Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 3', TRUE, 38),
        ('excel_crime_toi_loi_dung_cac_quyen_tu_do_dan_chu_xam_pham_loi_ich_cua_nha_nuoc_quyen_loi_ic_289ffab7', 'Tội lợi dụng các quyền tự do dân chủ xâm phạm lợi ích của Nhà nước, quyền, lợi ích hợp pháp của tổ chức, cá nhân', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 39),
        ('excel_crime_toi_loi_dung_chuc_vu_quyen_han_trong_khi_thi_hanh_cong_vu', 'Tội lợi dụng chức vụ, quyền hạn trong khi thi hành công vụ', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 7', TRUE, 40),
        ('excel_crime_toi_lua_ao_chiem_oat_tai_san', 'Tội lừa đảo chiếm đoạt tài sản', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 137', TRUE, 41),
        ('excel_crime_toi_moi_gioi_hoi_lo', 'Tội môi giới hối lộ', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 6', TRUE, 42),
        ('excel_crime_toi_moi_gioi_mai_dam', 'Tội môi giới mại dâm', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 43),
        ('excel_crime_toi_mua_ban_trai_phep_chat_ma_tuy', 'Tội mua bán trái phép chất ma túy', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 62', TRUE, 44),
        ('excel_crime_toi_nhan_hoi_lo', 'Tội nhận hối lộ', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 28', TRUE, 45),
        ('excel_crime_toi_san_xuat_buon_ban_hang_cam', 'Tội sản xuất, buôn bán hàng cấm', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 5', TRUE, 46),
        ('excel_crime_toi_san_xuat_buon_ban_hang_gia', 'Tội sản xuất, buôn bán hàng giả', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 47),
        ('excel_crime_toi_san_xuat_buon_ban_hang_gia_la_thuc_an_dung_e_chan_nuoi_phan_bon_thuoc_thu_y_476861cc', 'Tội sản xuất, buôn bán hàng giả là thức ăn dùng để chăn nuôi, phân bón, thuốc thú y, thuốc bảo vệ thực vật, giống cây trồng, giống vật nuôi', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 48),
        ('excel_crime_toi_san_xuat_mua_ban_trao_oi_hoac_tang_cho_cong_cu_thiet_bi_phan_mem_e_su_dung_d8026a65', 'Tội sản xuất, mua bán, trao đổi hoặc tặng cho công cụ, thiết bị, phần mềm để sử dụng vào mục đích trái pháp luật', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 49),
        ('excel_crime_toi_san_xuat_trai_phep_chat_ma_tuy', 'Tội sản xuất trái phép chất ma túy', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 50),
        ('excel_crime_toi_su_dung_con_dau_hoac_tai_lieu_gia_cua_co_quan_to_chuc', 'tội sử dụng con dấu hoặc tài liệu giả của cơ quan, tổ chức', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 22', TRUE, 51),
        ('excel_crime_toi_su_dung_mang_may_tinh_mang_vien_thong_phuong_tien_ien_tu_thuc_hien_hanh_vi_56cd5f46', 'Tội sử dụng mạng máy tính, mạng viễn thông, phương tiện điện tử thực hiện hành vi chiếm đoạt tài sản', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 3', TRUE, 52),
        ('excel_crime_toi_su_dung_trai_phep_chat_ma_tuy', 'Tội sử dụng trái phép chất ma túy', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 53),
        ('excel_crime_toi_sua_chua_va_su_dung_giay_chung_nhan_cac_tai_lieu_cua_co_quan_to_chuc', 'Tội sửa chữa và sử dụng giấy chứng nhận, các tài liệu của cơ quan, tổ chức', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 54),
        ('excel_crime_toi_tang_tru_trai_phep_chat_ma_tuy', 'Tội tàng trữ trái phép chất ma túy', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 44', TRUE, 55),
        ('excel_crime_toi_tang_tru_van_chuyen_hang_cam', 'Tội tàng trữ, vận chuyển hàng cấm', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 6', TRUE, 56),
        ('excel_crime_toi_tham_o_tai_san', 'Tội tham ô tài sản', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 62', TRUE, 57),
        ('excel_crime_toi_thieu_trach_nhiem_gay_hau_qua_nghiem_trong', 'Tội thiếu trách nhiệm gây hậu quả nghiêm trọng', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 31', TRUE, 58),
        ('excel_crime_toi_to_chuc_anh_bac_hoac_ga_bac', 'Tội tổ chức đánh bạc hoặc gá bạc', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 92', TRUE, 59),
        ('excel_crime_toi_to_chuc_moi_gioi_cho_nguoi_khac_xuat_canh_nhap_canh_hoac_o_lai_viet_nam_trai_phep', 'Tội tổ chức, môi giới cho người khác xuất cảnh, nhập cảnh hoặc ở lại Việt Nam trái phép', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 15', TRUE, 60),
        ('excel_crime_toi_to_chuc_su_dung_trai_phep_chat_ma_tuy', 'Tội tổ chức sử dụng trái phép chất ma túy', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 67', TRUE, 61),
        ('excel_crime_toi_trom_cap_tai_san', 'Tội trộm cắp tài sản', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 87', TRUE, 62),
        ('excel_crime_toi_ua_hoi_lo', 'Tội đưa hối lộ', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 11', TRUE, 63),
        ('excel_crime_toi_van_chuyen_trai_phep_chat_ma_tuy', 'Tội vận chuyển trái phép chất ma túy', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 22', TRUE, 64),
        ('excel_crime_toi_vi_pham_quy_inh_ve_an_toan_thuc_pham', 'Tội vi phạm quy định về an toàn thực phẩm', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 65),
        ('excel_crime_toi_vi_pham_quy_inh_ve_au_thau_gay_hau_qua_nghiem_trong', 'Tội vi phạm quy định về đấu thầu gây hậu quả nghiêm trọng', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 33', TRUE, 66),
        ('excel_crime_toi_vi_pham_quy_inh_ve_au_tu_cong_trinh_xay_dung_gay_hau_qua_nghiem_trong', 'Tội vi phạm quy định về đầu tư công trình xây dựng gây hậu quả nghiêm trọng', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 12', TRUE, 67),
        ('excel_crime_toi_vi_pham_quy_inh_ve_boi_thuong_ho_tro_tai_inh_cu_khi_nha_nuoc_thu_hoi_at', 'Tội vi phạm quy định về bồi thường, hỗ trợ, tái định cư khi Nhà nước thu hồi đất', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 4', TRUE, 68),
        ('excel_crime_toi_vi_pham_quy_inh_ve_ieu_khien_phuong_tien_giao_thong_uong_thuy', 'Tội vi phạm quy định về điều khiển phương tiện giao thông đường thủy', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 69),
        ('excel_crime_toi_vi_pham_quy_inh_ve_ke_toan_gay_hau_qua_nghiem_trong', 'Tội vi phạm quy định về kế toán gây hậu quả nghiêm trọng', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 3', TRUE, 70),
        ('excel_crime_toi_vi_pham_quy_inh_ve_khai_thac_bao_ve_rung_va_lam_san', 'Tội vi phạm quy định về khai thác, bảo vệ rừng và lâm sản', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 71),
        ('excel_crime_toi_vi_pham_quy_inh_ve_nghien_cuu_tham_do_khai_thac_tai_nguyen', 'Tội vi phạm quy định về nghiên cứu, thăm dò, khai thác tài nguyên', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 7', TRUE, 72),
        ('excel_crime_toi_vi_pham_quy_inh_ve_phong_chay_chua_chay', 'Tội vi phạm quy định về phòng cháy, chữa cháy', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 73),
        ('excel_crime_toi_vi_pham_quy_inh_ve_quan_ly_su_dung_tai_san_nha_nuoc_gay_that_thoat_lang_phi', 'Tội vi phạm quy định về quản lý, sử dụng tài sản Nhà nước gây thất thoát, lãng phí', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 74),
        ('excel_crime_toi_vi_pham_quy_inh_ve_tham_gia_giao_thong_uong_bo', 'Tội vi phạm quy định về tham gia giao thông đường bộ', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 83', TRUE, 75),
        ('excel_crime_toi_vi_pham_viec_niem_phong_ke_bien_tai_san_phong_toa_tai_khoan', 'Tội vi phạm việc niêm phong, kê biên tài sản, phong tỏa tài khoản', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 76),
        ('excel_crime_toi_vo_y_gay_thuong_tich_hoac_gay_ton_hai_cho_suc_khoe_cua_nguoi_khac', 'Tội vô ý gây thương tích hoặc gây tổn hại cho sức khỏe của người khác', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 77),
        ('excel_crime_toi_vo_y_lam_chet_nguoi', 'Tội vô ý làm chết người', 'Hình sự - Phúc thẩm.xlsx; Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 4', TRUE, 78),
        ('excel_crime_toi_xam_nhap_trai_phep_vao_mang_may_tinh_mang_vien_thong_hoac_phuong_tien_ien_t_a173ea5a', 'Tội xâm nhập trái phép vào mạng máy tính, mạng viễn thông hoặc phương tiện điện tử của người khác', 'Hình sự - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 79),
        ('excel_crime_toi_xam_pham_thi_the_mo_ma_hai_cot', 'Tội xâm phạm thi thể, mồ mả, hài cốt', 'Hình sự - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 80)
)
INSERT INTO dm_crimes (crime_code, crime_name, source_document, notes, requires_human_review, sort_order)
SELECT s.crime_code, s.crime_name, s.source_document, s.notes, s.requires_human_review, s.sort_order
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM dm_crimes c WHERE lower(btrim(c.crime_name)) = lower(btrim(s.crime_name)))
ON CONFLICT (crime_code) DO UPDATE SET crime_name = EXCLUDED.crime_name, source_document = EXCLUDED.source_document, notes = EXCLUDED.notes, requires_human_review = EXCLUDED.requires_human_review, sort_order = EXCLUDED.sort_order, is_active = TRUE;
