-- Seed 024: Excel-derived marriage-family, business-commercial and labor categories.
-- Source: database/seed/danh sach/*.xlsx

WITH src(relationship_code, relationship_name, case_type_scope, source_document, notes, requires_human_review, sort_order) AS (
    VALUES
        ('excel_rel_chia_tai_san_chung_sau_khi_ly_hon', 'Chia tài sản chung sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 1),
        ('excel_rel_chia_tai_san_sau_khi_ly_hon', 'Chia tài sản sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 2),
        ('excel_rel_cong_nhan_thuan_tinh_ly_hon', 'Công nhận thuận tình ly hôn', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 3),
        ('excel_rel_khoi_kien_ly_hon', 'Khởi kiện ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 4),
        ('excel_rel_khong_cong_nhan_vo_chong_tranh_chap_quyen_nuoi_con', 'Không công nhận vợ chồng, tranh chấp quyền nuôi con', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 5),
        ('excel_rel_ly_hon', 'Ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx; Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 34', TRUE, 6),
        ('excel_rel_ly_hon_chia_tai_san_chung', 'Ly hôn, chia tài sản chung', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 7),
        ('excel_rel_ly_hon_chia_tai_san_chung_khi_ly_hon', 'Ly hôn, chia tài sản chung khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 8),
        ('excel_rel_ly_hon_chia_tai_san_chung_tra_no_chung', 'Ly hôn, chia tài sản chung, trả nợ chung', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 9),
        ('excel_rel_ly_hon_chia_tai_san_khi_ly_hon', 'Ly hôn, chia tài sản khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 10),
        ('excel_rel_ly_hon_tranh_chap_chia_tai_san_chung', 'Ly hôn, tranh chấp chia tài sản chung', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 11),
        ('excel_rel_ly_hon_tranh_chap_chia_tai_san_khi_ly_hon', 'Ly hôn, tranh chấp chia tài sản khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 12),
        ('excel_rel_ly_hon_tranh_chap_nuoi_con', 'Ly hôn, tranh chấp nuôi con', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx; Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 3', TRUE, 13),
        ('excel_rel_ly_hon_tranh_chap_nuoi_con_chia_tai_san', 'Ly hôn , tranh chấp nuôi con, chia tài sản', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 14),
        ('excel_rel_ly_hon_tranh_chap_nuoi_con_chia_tai_san_khi_ly_hon', 'Ly hôn, tranh chấp nuôi con chia tài sản khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 15),
        ('excel_rel_ly_hon_tranh_chap_nuoi_con_khi_ly_hon', 'Ly hôn, tranh chấp nuôi con khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 16),
        ('excel_rel_ly_hon_tranh_chap_ve_nuoi_con', 'Ly hôn, tranh chấp về nuôi con', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx; Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 14', TRUE, 17),
        ('excel_rel_ly_hon_tranh_chap_ve_nuoi_con_chia_tai_san_chung_khi_ly_hon', 'Ly hôn, tranh chấp về nuôi con, chia tài sản chung khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 18),
        ('excel_rel_ly_hon_tranh_chap_ve_nuoi_con_chung', 'Ly hôn, tranh chấp về nuôi con chung', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 19),
        ('excel_rel_ly_hon_tranh_chap_ve_nuoi_con_khi_ly_hon', 'Ly hôn, tranh chấp về nuôi con khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx; Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 12', TRUE, 20),
        ('excel_rel_ly_hon_tranh_chap_ve_nuoi_con_khi_ly_hon_nghia_vu_tra_no_chung_khi_ly_hon', 'Ly hôn, tranh chấp về nuôi con khi ly hôn, nghĩa vụ trả nợ chung khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 21),
        ('excel_rel_ly_hon_tranh_chap_ve_nuoi_con_va_cap_duong_nuoi_con_khi_ly_hon', 'Ly hôn, tranh chấp về nuôi con và cấp dưỡng nuôi con khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 22),
        ('excel_rel_ly_hon_tranh_chap_ve_nuoi_con_va_nghia_vu_tra_no_chung_khi_ly_hon', 'ly hôn, tranh chấp về nuôi con và nghĩa vụ trả nợ chung khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 23),
        ('excel_rel_ly_hon_tranh_chap_ve_tai_san_chung', 'Ly hôn, tranh chấp về tài sản chung', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 24),
        ('excel_rel_ly_hon_va_tranh_chap_nuoi_con_chung', 'Ly hôn và tranh chấp nuôi con chung', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 25),
        ('excel_rel_ly_lon_tranh_chap_ve_nuoi_con', 'Ly lôn, tranh chấp về nuôi con', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 26),
        ('excel_rel_mau_thuan_gia_inh', 'Mâu thuẫn gia đình', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 27),
        ('excel_rel_thay_oi_nguoi_truc_tiep_nuoi_con', 'Thay đổi người trực tiếp nuôi con', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx; Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 28),
        ('excel_rel_tranh_chap_chia_tai_san_chung_cua_nam_nu_song_chung_voi_nhau_nhu_vo_chong', 'Tranh chấp chia tài sản chung của nam nữ sống chung với nhau như vợ chồng', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 29),
        ('excel_rel_tranh_chap_chia_tai_san_chung_sau_khi_ly_hon', 'tranh chấp chia tài sản chung sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 30),
        ('excel_rel_tranh_chap_chia_tai_san_sau_khi_ly_hon', 'Tranh chấp chia tài sản sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 31),
        ('excel_rel_tranh_chap_chia_tai_san_sau_ly_hon', 'Tranh chấp chia tài sản sau ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 32),
        ('excel_rel_tranh_chap_chia_tai_san_sau_ly_hon_tranh_chap_hop_ong_vay_tai_san', 'Tranh chấp chia tài sản sau ly hôn, tranh chấp hợp đồng vay tài sản', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 33),
        ('excel_rel_tranh_chap_ve_chia_tai_san_chung_cua_vo_chong_sau_ly_hon', 'Tranh chấp vê chia tài sản chung của vợ chồng sau ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 34),
        ('excel_rel_tranh_chap_ve_chia_tai_san_sau_khi_ly_hon', 'Tranh chấp về chia tài sản sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 35),
        ('excel_rel_tranh_chap_ve_nuoi_con_xac_inh_cha_cho_con', 'tranh chấp về nuôi con, xác định cha cho con', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 36),
        ('excel_rel_tranh_chap_ve_tai_san_chung_cua_vo_chong_sau_ly_hon', 'Tranh chấp về tài sản chung của vợ chồng sau ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 37),
        ('excel_rel_tranh_chap_ve_thay_oi_nguoi_truc_tiep_nuoi_con_chia_tai_san_sau_khi_ly_hon', 'Tranh chấp về thay đổi người trực tiếp nuôi con , chia tài sản sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 38),
        ('excel_rel_tranh_chap_ve_thay_oi_nguoi_truc_tiep_nuoi_con_sau_khi_ly_hon', 'Tranh chấp về thay đổi người trực tiếp nuôi con sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 39),
        ('excel_rel_tranh_chap_xac_inh_con_cho_me', 'Tranh chấp xác định con cho mẹ', 'marriage_family', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 40),
        ('excel_rel_xin_ly_hon', 'Xin ly hôn', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 41),
        ('excel_rel_yeu_cau_cong_nhan_thuan_tinh_ly_hon', 'Yêu cầu công nhận thuận tình ly hôn', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 42),
        ('excel_rel_yeu_cau_cong_nhan_thuan_tinh_ly_hon_thoa_thuan_nuoi_con', 'Yêu cầu công nhận thuận tình ly hôn, thỏa thuận nuôi con', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 43),
        ('excel_rel_yeu_cau_cong_nhan_ve_thay_oi_nguoi_truc_tiep_nuoi_con_sau_khi_ly_hon', 'Yêu cầu công nhận về thay đổi người trực tiếp nuôi con sau khi ly hôn', 'marriage_family', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 44),
        ('excel_rel_h_tin_dung', 'HĐ tín dụng', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 45),
        ('excel_rel_huy_hop_ong_kinh_te', 'huỷ hợp đồng kinh tế', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 46),
        ('excel_rel_kien_hop_ong', 'Kiện hợp đồng', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 47),
        ('excel_rel_nghia_vu_thanh_toan_tien', 'Nghĩa vụ thanh toán tiền', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 48),
        ('excel_rel_tranh_chap_giua_cong_ty_voi_cac_thanh_vien_cong_ty', 'Tranh chấp giữa Công ty với các thành viên Công ty', 'business_commercial', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 49),
        ('excel_rel_tranh_chap_giua_nguoi_chua_phai_la_thanh_vien_cong_ty_nhung_co_giao_dich_ve_chuyen_nhuong_phan_von_gop_voi_cong_ty', 'Tranh chấp giữa người chưa phải là thành viên công ty nhưng có giao dịch về chuyển nhượng phần vốn góp với công ty', 'business_commercial', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 50),
        ('excel_rel_tranh_chap_hop_ong_chuyen_nhuong_tai_san_va_yeu_cau_boi_thuong_thiet_hai_ngoai_hop_ong', 'tranh chấp hợp đồng chuyển nhượng tài sản và yêu cầu bồi thường thiệt hại ngoài hợp đồng', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 51),
        ('excel_rel_tranh_chap_hop_ong_chuyen_nhuong_von_gop', 'Tranh chấp hợp đồng chuyển nhượng vốn góp', 'business_commercial', 'Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 52),
        ('excel_rel_tranh_chap_hop_ong_dich_vu', 'Tranh chấp hợp đồng dịch vụ', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 53),
        ('excel_rel_tranh_chap_hop_ong_hop_tac_au_tu', 'tranh chấp hợp đồng hợp tác đầu tư', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 54),
        ('excel_rel_tranh_chap_hop_ong_kinh_te', 'Tranh chấp hợp đồng kinh tế', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 4', TRUE, 55),
        ('excel_rel_tranh_chap_hop_ong_mua_ban_hang_hoa', 'Tranh chấp hợp đồng mua bán hàng hóa', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 56),
        ('excel_rel_tranh_chap_hop_ong_mua_ban_hang_hoa_yeu_cau_thanh_toan_tiem_mua_thiet_bi_hang_hai_thanh_toan_tien_lai_cham_tra_chi_phi_phat_sinh_c', 'tranh chấp hợp đồng mua bán hàng hóa (yêu cầu thanh toán tiềm mua thiết bị hàng hải, thanh toán tiền lãi chậm trả, chi phí phát sinh chạy thử và tranh chấp về nghĩa vụ bảo hành thiết bị hàng hóa', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 57),
        ('excel_rel_tranh_chap_hop_ong_sua_chua_inh_ky_tau_bien', 'Tranh chấp hợp đồng sửa chữa định kỳ tàu biển', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 58),
        ('excel_rel_tranh_chap_hop_ong_thi_cong_xay_lap_cong_trinh', 'Tranh chấp hợp đông thi công, xây lắp công trình', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 59),
        ('excel_rel_tranh_chap_hop_ong_thue_tai_san', 'Tranh chấp hợp đồng thuê tài sản', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 60),
        ('excel_rel_tranh_chap_hop_ong_tin_dung', 'Tranh chấp hợp đồng tín dụng', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx; Dân sự mở rộng - Sơ thẩm.xlsx', 'Sheet: Projects 3; count: 12', TRUE, 61),
        ('excel_rel_tranh_chap_hop_ong_tin_dung_tranh_chap_hop_ong_chuyen_nhuong_quyen_su_dung_at_va_yeu_cau_tuyen_bo_hop_ong_the_chap_quyen_su_dung_a', 'tranh chấp hợp đồng tín dụng, tranh chấp hợp đồng chuyển nhượng quyền sử dụng đất và yêu cầu tuyên bố hợp đồng thế chấp quyền sử dụng đất vô hiệu', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 62),
        ('excel_rel_tranh_chap_hop_ong_tin_dung_va_hop_ong_the_chap_tai_san', 'Tranh chấp hợp đồng tín dụng và hợp đồng thế chấp tài sản', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 2', TRUE, 63),
        ('excel_rel_tranh_chap_ve_hop_ong_bao_hiem', 'Tranh chấp về hợp đồng bảo hiểm', 'business_commercial', 'Dân sự mở rộng - Phúc thẩm.xlsx', 'Sheet: Projects 3; count: 1', TRUE, 64)
)
INSERT INTO dm_legal_relationships (relationship_code, relationship_name, case_type_scope, source_document, notes, requires_human_review, sort_order)
SELECT s.relationship_code, s.relationship_name, s.case_type_scope, s.source_document, s.notes, s.requires_human_review, s.sort_order
FROM src s
WHERE NOT EXISTS (SELECT 1 FROM dm_legal_relationships r WHERE lower(btrim(r.relationship_name)) = lower(btrim(s.relationship_name)) AND COALESCE(r.case_type_scope, '') = COALESCE(s.case_type_scope, ''))
ON CONFLICT (relationship_code) DO UPDATE SET relationship_name = EXCLUDED.relationship_name, case_type_scope = EXCLUDED.case_type_scope, source_document = EXCLUDED.source_document, notes = EXCLUDED.notes, requires_human_review = EXCLUDED.requires_human_review, sort_order = EXCLUDED.sort_order, is_active = TRUE;
